### ISSUE TITLE
Changing Roundtrip People Example To Use Option instead of Vec fails

### ISSUE THREAD

**Issue by LordAldaron** [muon-data/muon-rs#11]
Take, for example, this muon-rs program that works.  `label` is being treated as a substitute.

```rust
use muon_rs as muon;
use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, PartialEq)]
struct Groups {
    group: Vec<Group>,
}

#[derive(Debug, Deserialize, Serialize, PartialEq)]
struct Group {
    label: String,
}

#[test]
fn people() -> muon::Result<()> {
    // No dictators, only 1 philosopher
    const PEOPLE: &str = "group: dictators\n";

    let g: Groups = muon::from_str(PEOPLE)?;
    assert_eq!(muon::to_string(&g)?, PEOPLE);
    Ok(())
}
```

Now, if you replace

```rust
struct Groups {
    group: Vec<Group>,
}
```

with

```rust
struct Groups {
    group: Option<Group>,
}
```

it doesn't gives error `FailedParse(InvalidSubstitute)` because now MuON is trying to interpret that as the group record being substituted, when (I think) it should be the `label` record being substituted.  The MuON spec says

> substitution is only allowed for text, bool, int, number, datetime, date and time types without optional or list modifiers

So either way there is an inconsistency because it works with list modifiers but not optional.  But, I think the list behaviour makes more sense, substituting within the record should be possible, just not substituting of the record itself.

**Edit**: Changed to be a simpler example with better explanations.

**Comment by DougLau** [comment]
Fixed in 0.2.2
